name: Destroy Terraform Environment

on:
  workflow_dispatch:
    inputs:
      parameter-name:
        description: 'Destroy Infrastructure'
        required: true

jobs:
  Destroy_Infrastructure:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 1
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init
       

      - name: Destroy infrastructure
        run: terraform destroy -auto-approve
       
